### ISSUE TITLE
Tearing down deployment shows error

### ISSUE THREAD

**Issue by brejoc** [flavio/salt-kubernetes-demo#1]
When tearing down a deployment (your Nginx example in that case) I'm getting an error. I'm not sure why this happens. Perhaps you can help me. This is the result of tearing the Nginx example deployment down again after successfully deploying it to the Kubernetes cluster:

```
$ salt "*" state.highstate                                                               
kubernetes:
----------
          ID: nginx-source
    Function: kubernetes.deployment_absent
      Result: False
     Comment: Something went wrong, response: {'status': "{u'observedGeneration': 1, u'updatedReplicas': 1, u'availableReplicas': 1, u'conditions': [{u'status': u'True', u'lastUpdateTime': u'2017-08-10T06:15:50Z', u'lastTransitionTime': u'2017-08-10T06:15:50Z', u'reason': u'MinimumReplicasAvailable', u'message': u'Deployment has minimum availability.', u'type': u'Available'}], u'replicas': 1}", 'kind': 'Deployment', 'code': None, 'reason': None, 'details': None, 'message': None, 'api_version': 'extensions/v1beta1', 'metadata': {'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/nginx-source', 'resource_version': '2229697'}}
     Started: 08:16:19.836631
    Duration: 279.435 ms
     Changes:   
----------
          ID: nginx-source-template
    Function: kubernetes.deployment_absent
      Result: False
     Comment: Something went wrong, response: {'status': "{u'observedGeneration': 1, u'updatedReplicas': 1, u'availableReplicas': 1, u'conditions': [{u'status': u'True', u'lastUpdateTime': u'2017-08-10T06:15:50Z', u'lastTransitionTime': u'2017-08-10T06:15:50Z', u'reason': u'MinimumReplicasAvailable', u'message': u'Deployment has minimum availability.', u'type': u'Available'}], u'replicas': 1}", 'kind': 'Deployment', 'code': None, 'reason': None, 'details': None, 'message': None, 'api_version': 'extensions/v1beta1', 'metadata': {'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/nginx-source-template', 'resource_version': '2229700'}}
     Started: 08:16:20.116494
    Duration: 88.025 ms
     Changes:   
----------
          ID: my-nginx
    Function: kubernetes.deployment_absent
      Result: False
     Comment: Something went wrong, response: {'status': "{u'observedGeneration': 1}", 'kind': 'Deployment', 'code': None, 'reason': None, 'details': None, 'message': None, 'api_version': 'extensions/v1beta1', 'metadata': {'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/my-nginx', 'resource_version': '2229702'}}
     Started: 08:16:20.204916
    Duration: 74.603 ms
     Changes:   

Summary for kubernetes
------------
Succeeded: 0
Failed:    3
------------
Total states run:     3
Total run time: 442.063 ms
ERROR: Minions returned with non-zero exit code
```

# Steps to reproduce

1. Install Salt. I've tried it with version 2016.11.4 with OpenSUSE patches and with release version 2017.7.0.
2. Install [Kubernetes Python client version 1.0.2](https://pypi.python.org/pypi/kubernetes/1.0.2).
3. Setting up Pillars config with local Kubernetes cluster.
4. Fetching the most recent module and state file from Salt upstream.
5. Fetching the Nginx example from this repo: `k8s-nginx-deployments-absent` and `k8s-nginx-deployments-present`
6. Making a deployment with `k8s-nginx-deployments-present` and checking with kubectl that everything works
7. Tearing the deployment down with `k8s-nginx-deployments-absent`.

### Result

The Kubernetes module show the above mentioned error message but successfully tears down the deployment.

### Expected result

The Kubernetes modul tears down the deployment and tells me that everything worked.

**Comment by brejoc** [comment]
Something that caught my eye was this part from the kubernetes response:

```json
    "status":{
        "observedGeneration":1,
        "replicas":1,
        "updatedReplicas":1,
        "availableReplicas":1,
        "conditions":[
            {
                "type":"Available",
                "status":"True",
                "lastUpdateTime":"2017-08-15T11:55:33Z",
                "lastTransitionTime":"2017-08-15T11:55:33Z",
                "reason":"MinimumReplicasAvailable",
                "message":"Deployment has minimum availability."
            }
        ]
    }
```

Shouldn't the vars `replicas`, `updatedReplicas`, `availableReplicas` show something different?

**Comment by ereslibre** [comment]
One thing that surprises me here is the raw response you are getting:

`Something went wrong, response: {'status': "{u'observedGeneration': 1, u'updatedReplicas': 1, u'availableReplicas': 1, u'conditions': [{u'status': u'True', u'lastUpdateTime': u'2017-08-10T06:15:50Z', u'lastTransitionTime': u'2017-08-10T06:15:50Z', u'reason': u'MinimumReplicasAvailable', u'message': u'Deployment has minimum availability.', u'type': u'Available'}], u'replicas': 1}", 'kind': 'Deployment', 'code': None, 'reason': None, 'details': None, 'message': None, 'api_version': 'extensions/v1beta1', 'metadata': {'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/nginx-source', 'resource_version': '2229697'}}`

Looking at `'code': None` specifically... the original source code expects a `200` http result: https://github.com/saltstack/salt/blob/develop/salt/states/kubernetes.py#L135-L143

**Comment by brejoc** [comment]
This is what we are getting from [delete_namespaced_deployment_with_http_info()](https://github.com/kubernetes-incubator/client-python/blob/release-1.0/kubernetes/client/apis/extensions_v1beta1_api.py#L2359) from the the Kubernetes client lib:
```python
{'api_version': 'extensions/v1beta1',
 'code': None,
 'details': None,
 'kind': 'Deployment',
 'message': None,
 'metadata': {'resource_version': '6894440',
              'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/my-nginx'},
 'reason': None,
 'status': "{u'observedGeneration': 1}"}
```

Since `code` is already `None` there, the root cause has to be in the client lib.

**Comment by flavio** [comment]
Yeah, @ereslibre told me about that. This is happening also in other places of the API, as far as I remember it happens also when deleting a namespace. All the operations taking quite some time lack a return code and provide a different request when they are "in progress".

This is something that has to be handled by the salt module, but needs a proper fix on the python library and eventually inside of kubernetes itself.

We can help with the latter. I think you can cover the salt module and the python library :)

**Comment by brejoc** [comment]
@flavio @ereslibre Do you know if there is anything else besides `delete_deployment()` that has that kind of response? I've tested everything but `delete_configmap()` and never receive a return with `code` None.

**Comment by ereslibre** [comment]
@brejoc Cannot confirm, but @flavio commented that this happens also when deleting a namespace (but from your comment I guess you are not hitting this behaviour). It's not implemented, but I'd expect this kind of response to come from a deletion of a daemon set, for example.

To be honest, since there exists a sync and an async way of calling on the python library of kubernetes I'd expect the sync one to return iff there's a response (it can take a while, okay, I asked for the sync call). If I'm not interested in an immediate response I'd use the async version and my callback would take care of everything.

**Comment by brejoc** [comment]
@ereslibre Thanks! I've checked again and `delete_namespace` indeed also returns `None`. But the kubernetes state file allows that. I've overseen this in the first run.

Update: I totally agree with you on the sync vs async topic. It's really confusing, that the Kubernets lib handles this in such a strange way.

**Comment by flavio** [comment]
I think we can close this issue, feel free to reopen if needed.
